# Generated by Django 2.1.1 on 2018-09-24 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_audio_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='freesound-frontend/public/audios', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='freesounduser',
            name='profile_picture',
            field=models.ImageField(upload_to='freesound-frontend/public/profile_pictures'),
        ),
    ]
